//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
    
  
namespace Online_Inventory.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using Online_Inventory.Models;

    public partial class Feedback
    {
        public string email { get; set; }
        [Required(ErrorMessage = "Fill Your Email Address Or Name")]

        public string subject { get; set; }
        [Required(ErrorMessage = "Subject Cant be Empty")]

        public string message { get; set; }

        public string ErrorMessage { get; set; }

    }
}