//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using Online_Inventory.Models;

namespace Online_Inventory.Models
{


    public partial class ProductTable
    {
        [Required(ErrorMessage = "Must have Product ID")]
        public int productId { get; set; }

        [Required(ErrorMessage = "Product must have a Name")]
        public string productName { get; set; }

        [Required(ErrorMessage = "Category Name Can't be left Blank")]
        public string categoryName { get; set; }

        [Required(ErrorMessage = "Cost Can't be 0")]
        public decimal productSP { get; set; }

        [Required(ErrorMessage = "Enter Quantity Here")]
        public int productQuantity { get; set; }
    }
}
